#!/bin/sh
# setup my mac app

# GITHUB_TOKEN=xxx
# touch ~/.git-credentials
# git config --global credential.helper store
# echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" >> ~/.git-credentials

if ! command -v brew >/dev/null; then
  echo "Installing Homebrew ..."
  curl -fsS \
    'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
fi

brew tap "homebrew/cask"
brew tap "universal-ctags/universal-ctags"

brew install \
  composer \
  fzf \
  f \
  highlight \
  icdiff \
  kubernetes-cli \
  mariadb \
  mycli \
  neovim \
  nginx \
  node \
  ntfs-3g \
  php \
  php-code-sniffer \
  python \
  ranger \
  reattach-to-user-namespace \
  redis \
  ripgrep \
  shellcheck \
  shfmt \
  speedtest-cli \
  sqlite \
  task \
  the_silver_searcher \
  tig \
  tldr \
  tmux \
  tree \
  universal-ctags \
  urlview \
  watch \
  wget \
  zsh \
  gnu-sed --with-default-names

brew cask install \
  appcleaner \
  bartender \
  bettertouchtool \
  dash \
  docker \
  dropbox \
  fantastical \
  firefox \
  gpg-suite \
  iterm2 \
  karabiner-elements \
  mounty \
  mtmr \
  osxfuse \
  postman \
  sequel-pro \
  sourcetree \
  steam \
  sublime-text \
  transmission \
  vimr \
  font-hasklig \ 
  kitty

brew tap homebrew/cask-fonts

zsh -c 'git clone --recursive https://github.com/zimfw/zimfw.git ${ZDOTDIR:-${HOME}}/.zim; exit'

sudo sh -c "echo $(which zsh) >> /etc/shells"
chsh -s $(which zsh)
