#!/bin/sh
# setup my mac app

# GITHUB_TOKEN=xxx
# touch ~/.git-credentials
# git config --global credential.helper store
# echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" >> ~/.git-credentials

if ! command -v brew >/dev/null; then
  echo "Installing Homebrew ..."
  curl -fsS \
    'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
fi

brew tap "homebrew/cask"
brew tap "universal-ctags/universal-ctags"

# neovim
brew install \
  fzf \
  fd \
  universal-ctags \
  neovim

brew install \
  composer \
  f \
  php \
  php-code-sniffer \
  reattach-to-user-namespace \
  ripgrep \
  the_silver_searcher \
  tldr \
  tmux \
  urlview \
  wget \
  zsh \
  gnu-sed --with-default-names

brew cask install \
  appcleaner \
  bartender \
  dash \
  fantastical \
  firefox \
  iterm2 \
  postman \
  sequel-pro \
  sourcetree \
  notion \
  tableplus \
  font-hasklig

brew tap homebrew/cask-fonts


sudo sh -c "echo $(which zsh) >> /etc/shells"
chsh -s $(which zsh)

# install zim, override dotfiles
# zsh -c 'git clone --recursive https://github.com/zimfw/zimfw.git ${ZDOTDIR:-${HOME}}/.zim; exit'
# prompt pure, font hasklight, theme gruvbox
# activate icloud, download vimwiki
# ln -s ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/vimwiki ~/vimwiki
# iterm
